after_success:
  - |
    if [ "$TRAVIS_PULL_REQUEST" == false ] && [ "$TRAVIS_BRANCH" == master ]; then
        echo $PGP_PUBLIC | base64 --decode > ~/.gnupg/pubring.gpg
        echo $PGP_SECRET | base64 --decode > ~/.gnupg/secring.gpg
        cd sbt-cross
        sbt publishSigned sonatypeReleaseAll
    fi
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
deploy:
  api_key: $GITHUB_AUTH
  file: "*/target*/**/*.jar"
  file_glob: true
  on:
    tags: true
  provider: releases
  skip_cleanup: true
git:
  depth: 1
jdk:
  - openjdk7
language: scala
script:
  - cd sbt-cross
  - sbt 'all checkFormat package test'
